#!/bin/bash

cmd="node server.js"

if [[ $1 = 'dev' ]]; then
    ${cmd}
else
    nohup ${cmd} >/dev/null 2>&1 &
    ./node_modules/.bin/mocha-phantomjs -R spec http://127.0.0.1:8080/test/index.html
    killall node
fi
